"""Add nba_game_id to Game model

Revision ID: 7687ffd6ee58
Revises: b9ab9f336a31
Create Date: 2024-05-14 00:54:27.557578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7687ffd6ee58'
down_revision: Union[str, None] = 'b9ab9f336a31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('nba_game_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'games', ['nba_game_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='unique')
    op.drop_column('games', 'nba_game_id')
    # ### end Alembic commands ###
