"""Begin proper revamp

Revision ID: 871d0224657c
Revises: 
Create Date: 2024-05-13 02:39:13.465749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '871d0224657c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('nba_player_id', sa.Integer(), nullable=True))
    op.drop_constraint('players_player_id_key', 'players', type_='unique')
    op.create_unique_constraint(None, 'players', ['nba_player_id'])
    op.drop_column('players', 'player_id')
    op.add_column('team_stats', sa.Column('nba_team_id', sa.Integer(), nullable=True))
    op.drop_constraint('team_stats_team_id_fkey', 'team_stats', type_='foreignkey')
    op.create_foreign_key(None, 'team_stats', 'teams', ['nba_team_id'], ['id'])
    op.drop_column('team_stats', 'team_id')
    op.add_column('teams', sa.Column('nba_team_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'teams', ['nba_team_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='unique')
    op.drop_column('teams', 'nba_team_id')
    op.add_column('team_stats', sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'team_stats', type_='foreignkey')
    op.create_foreign_key('team_stats_team_id_fkey', 'team_stats', 'teams', ['team_id'], ['id'])
    op.drop_column('team_stats', 'nba_team_id')
    op.add_column('players', sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'players', type_='unique')
    op.create_unique_constraint('players_player_id_key', 'players', ['player_id'])
    op.drop_column('players', 'nba_player_id')
    # ### end Alembic commands ###
