"""Add TeamRollingAverages class uc

Revision ID: 89be7ffc094f
Revises: cf5015bf34a9
Create Date: 2024-05-26 01:34:09.975521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89be7ffc094f'
down_revision: Union[str, None] = 'cf5015bf34a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_rolling_game_team_uc', 'team_rolling_averages', ['game_id', 'team_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_rolling_game_team_uc', 'team_rolling_averages', type_='unique')
    # ### end Alembic commands ###
