"""Add nba_game_id to Game model

Revision ID: b9ab9f336a31
Revises: 871d0224657c
Create Date: 2024-05-14 00:53:56.826139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9ab9f336a31'
down_revision: Union[str, None] = '871d0224657c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'nba_player_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('team_stats', sa.Column('team_id', sa.Integer(), nullable=True))
    op.drop_constraint('team_stats_nba_team_id_fkey', 'team_stats', type_='foreignkey')
    op.create_foreign_key(None, 'team_stats', 'teams', ['team_id'], ['id'])
    op.drop_column('team_stats', 'nba_team_id')
    op.alter_column('teams', 'nba_team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'nba_team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('team_stats', sa.Column('nba_team_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'team_stats', type_='foreignkey')
    op.create_foreign_key('team_stats_nba_team_id_fkey', 'team_stats', 'teams', ['nba_team_id'], ['id'])
    op.drop_column('team_stats', 'team_id')
    op.alter_column('players', 'nba_player_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
