"""Add season_type to Game model

Revision ID: d77f69f14b09
Revises: 7fcf1d6cc72e
Create Date: 2024-05-11 10:24:06.420728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd77f69f14b09'
down_revision: Union[str, None] = '7fcf1d6cc72e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('season_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'season_type')
    # ### end Alembic commands ###
