"""Add season info to Game model

Revision ID: e725160f284f
Revises: d77f69f14b09
Create Date: 2024-05-11 10:52:31.586913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e725160f284f'
down_revision: Union[str, None] = 'd77f69f14b09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('season', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'season')
    # ### end Alembic commands ###
